# Generated by Django 3.1.6 on 2021-02-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategoria',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.subcategoria'),
        ),
    ]
