# Generated by Django 2.2.3 on 2021-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_datos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activado',
            field=models.BooleanField(default=False),
        ),
    ]
