# Generated by Django 2.2.3 on 2021-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_usuario_activado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=1234567890, max_length=10),
        ),
    ]
