# Generated by Django 2.2.3 on 2021-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_auto_20210305_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='calle',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
